name: Photo Portfolio
favicon: null
layout_spectrum: 0.25463
typography_spectrum: 0.17072
title: 'Alec R. | Photo Portfolio'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69156316-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5b6b0'
    - '#dbdbd3'
    - '#93673a'
    - '#393937'
    - '#5d5d5d'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
