name: Photo Portfolio
favicon: null
layout_spectrum: 0.88943
typography_spectrum: 0.19915
title: Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#69839e'
    - '#284a6f'
    - '#e6e2df'
    - '#11223d'
    - '#839eb1'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
