name: Photo Portfolio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf0f1'
    - '#7e8c8d'
    - '#34495e'
    - '#f1c40f'
    - '#c1392b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.9128223459701985
purpose: []
