name: Photo Portfolio
favicon: null
layout_spectrum: 0.25908338092267513
typography_spectrum: 0.29945838381536305
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9903482452500612
  lightness: 0.5879830538760871
  saturation: 0.47447170154191554
  rhythmicContrast: 0.9128223459701985
purpose: []
