name: Photo Portfolio
favicon: null
layout_spectrum: 0.22339
typography_spectrum: 0.09261
title: 'Alec R. | Photo Portfolio'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69156316-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#69839e'
    - '#284a6f'
    - '#e6e2df'
    - '#11223d'
    - '#839eb1'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
